import { COUNTRIES } from "./data";
import { TRIVIA } from "./trivia";
import { useState, useCallback, useMemo, useRef, useEffect } from "react";
import Fuse from "fuse.js";
import { supabase, createProfile, updateProfile, getProfile, submitScore, getLeaderboard, subscribeToScores, createChallenge, getChallenge, submitChallengeResult } from "./supabase";
var FL=function(i){return "https://flagcdn.com/w320/"+i+".png";};
var FS=function(i){return "https://flagcdn.com/w80/"+i+".png";};
var vib=function(p){try{navigator.vibrate(p);}catch(e){}};
var hOk=function(){vib(50);};var hNo=function(){vib([30,50,30]);};
var heartbeat=function(){vib([100,50,100,50,100]);};
var shuffle=function(a){var r=a.slice();for(var i=r.length-1;i>0;i--){var j=~~(Math.random()*(i+1));var tmp=r[i];r[i]=r[j];r[j]=tmp;}return r;};
var BELTS=[
{name:"White Belt",fr:"Ceinture Blanche",ar:"الحزام الأبيض",es:"Cinturón Blanco",min:0,color:"#B0BEC5",dark:"#90A4AE"},
{name:"Yellow Belt",fr:"Ceinture Jaune",ar:"الحزام الأصفر",es:"Cinturón Amarillo",min:20,color:"#EAB308",dark:"#CA8A04"},
{name:"Orange Belt",fr:"Ceinture Orange",ar:"الحزام البرتقالي",es:"Cinturón Naranja",min:40,color:"#F97316",dark:"#EA580C"},
{name:"Green Belt",fr:"Ceinture Verte",ar:"الحزام الأخضر",es:"Cinturón Verde",min:60,color:"#2ECC71",dark:"#27AE60"},
{name:"Blue Belt",fr:"Ceinture Bleue",ar:"الحزام الأزرق",es:"Cinturón Azul",min:90,color:"#5B7FFF",dark:"#4A6AEE"},
{name:"Purple Belt",fr:"Ceinture Violette",ar:"الحزام البنفسجي",es:"Cinturón Violeta",min:120,color:"#9B59B6",dark:"#8E44AD"},
{name:"Brown Belt",fr:"Ceinture Marron",ar:"الحزام البني",es:"Cinturón Marrón",min:150,color:"#92400E",dark:"#78350F"},
{name:"Black Belt",fr:"Ceinture Noire",ar:"الحزام الأسود",es:"Cinturón Negro",min:180,color:"#1A1A2E",dark:"#0F0F1E"}
];
var gB=function(m){var b=BELTS[0];for(var i=0;i<BELTS.length;i++){if(m>=BELTS[i].min)b=BELTS[i];}return b;};
var nxB=function(m){for(var i=0;i<BELTS.length;i++){if(m<BELTS[i].min)return BELTS[i];}return null;};
var bN=function(b,l){return l==="fr"?b.fr:l==="ar"?b.ar:l==="es"?b.es:b.name;};
var $={bg:"#FFFFFF",card:"#FFFFFF",bdr:"#E8ECF0",faint:"#F4F6F8",ink:"#1A1A2E",sub:"#4A4A6A",mu:"#9494B0",pri:"#FF6B6B",priD:"#EE5A5A",priL:"#FFE8E8",sec:"#20B2AA",secD:"#1A9690",secL:"#E0F5F4",blu:"#5B7FFF",bluD:"#4A6AEE",bluL:"#E8EDFF",gld:"#FFB347",gldD:"#EEA030",gldL:"#FFF3E0",red:"#FF6B6B",redD:"#EE5A5A",redL:"#FFE8E8",ok:"#2ECC71",okD:"#27AE60",okL:"#E8F8EF",pur:"#9B59B6",purD:"#8E44AD",r:16};
var dk=function(d,l,da){return d?da:l;};
var D=COUNTRIES;
var ALL_COUNTRIES=[]; var seen={}; for(var i=0;i<D.length;i++){var nm=D[i].n.en;if(!seen[nm]){seen[nm]=1;ALL_COUNTRIES.push(nm);}}ALL_COUNTRIES.sort();
var fuseList=D.map(function(c){return {iso:c.i,en:c.n.en,fr:c.n.fr,ar:c.n.ar,es:c.n.es};});
var fuse=new Fuse(fuseList,{keys:["en","fr","ar","es"],threshold:0.25,includeScore:true});
var CC={All:$.pri,Africa:"#FFB347",Europe:"#5B7FFF",Asia:"#FF6B6B","North America":"#2ECC71","South America":"#9B59B6",Oceania:"#FF69B4"};
var CONTS=["All","Africa","Europe","Asia","North America","South America","Oceania"];
var SR=[3,8,20,50];
var LCOL={en:"#5B7FFF",fr:"#FF6B6B",es:"#FFB347",ar:"#2ECC71"};
var VCARDS=[
{color:$.pri,bg:$.priL,title:{en:"Master Every Flag",fr:"Maîtrisez chaque drapeau",ar:"أتقن كل علم",es:"Domina cada bandera"},desc:{en:"Can you tell Chad from Romania?",fr:"Distinguez le Tchad de la Roumanie",ar:"هل تميز تشاد عن رومانيا؟",es:"¿Distingues Chad de Rumanía?"}},
{color:$.gld,bg:$.gldL,title:{en:"Earn Your Black Belt",fr:"Gagnez la ceinture noire",ar:"احصل على الحزام الأسود",es:"Gana el cinturón negro"},desc:{en:"8 ranks. Train daily. Prove mastery.",fr:"8 rangs. Prouvez votre maîtrise.",ar:"8 مراتب. تدرب يومياً.",es:"8 rangos. Demuestra tu dominio."}},
{color:$.blu,bg:$.bluL,title:{en:"Challenge the World",fr:"Défiez le monde",ar:"تحدى العالم",es:"Desafía al mundo"},desc:{en:"Compete on the global leaderboard.",fr:"Rivalisez au classement mondial.",ar:"نافس على الترتيب العالمي.",es:"Compite en el ranking mundial."}}
];
var ACHIEVEMENTS=[
{id:"first",icon:"F",c:$.pri,name:{en:"First Win",fr:"Première victoire",ar:"أول فوز",es:"Primera victoria"},desc:{en:"Complete a quiz",fr:"Terminez un quiz",ar:"أكمل اختبار",es:"Completa un quiz"},check:function(ms){return Object.values(ms).some(function(m){return m.s>0;});}},
{id:"f10",icon:"10",c:$.sec,name:{en:"Explorer",fr:"Explorateur",ar:"مستكشف",es:"Explorador"},desc:{en:"Master 10 flags",fr:"10 drapeaux",ar:"10 أعلام",es:"10 banderas"},check:function(ms,mc){return mc>=10;}},
{id:"f50",icon:"50",c:$.blu,name:{en:"Expert",fr:"Expert",ar:"خبير",es:"Experto"},desc:{en:"Master 50 flags",fr:"50 drapeaux",ar:"50 علم",es:"50 banderas"},check:function(ms,mc){return mc>=50;}},
{id:"f100",icon:"C",c:$.gld,name:{en:"Flag Master",fr:"Maître",ar:"سيد الأعلام",es:"Maestro"},desc:{en:"Master 100 flags",fr:"100 drapeaux",ar:"100 علم",es:"100 banderas"},check:function(ms,mc){return mc>=100;}},
{id:"s5",icon:"5x",c:"#F97316",name:{en:"Hot Streak",fr:"Série chaude",ar:"سلسلة حارة",es:"Racha"},desc:{en:"5x streak",fr:"Série 5x",ar:"سلسلة 5",es:"Racha 5x"},check:function(ms,mc,bk){return bk>=5;}},
{id:"s10",icon:"10x",c:$.pri,name:{en:"Streak King",fr:"Roi des séries",ar:"ملك السلاسل",es:"Rey de rachas"},desc:{en:"10x streak",fr:"Série 10x",ar:"سلسلة 10",es:"Racha 10x"},check:function(ms,mc,bk){return bk>=10;}},
{id:"yb",icon:"Y",c:"#EAB308",name:{en:"Yellow Belt",fr:"Ceinture jaune",ar:"حزام أصفر",es:"Cinturón amarillo"},desc:{en:"Reach Yellow Belt",fr:"Ceinture jaune",ar:"الحزام الأصفر",es:"Cinturón amarillo"},check:function(ms,mc){return mc>=20;}},
{id:"gb",icon:"G",c:"#2ECC71",name:{en:"Green Belt",fr:"Ceinture verte",ar:"حزام أخضر",es:"Cinturón verde"},desc:{en:"Reach Green Belt",fr:"Ceinture verte",ar:"الحزام الأخضر",es:"Cinturón verde"},check:function(ms,mc){return mc>=60;}},
{id:"bb",icon:"B",c:"#1A1A2E",name:{en:"Black Belt",fr:"Ceinture noire",ar:"حزام أسود",es:"Cinturón negro"},desc:{en:"Reach Black Belt",fr:"Ceinture noire",ar:"الحزام الأسود",es:"Cinturón negro"},check:function(ms,mc){return mc>=180;}}
];
var OT={en:{next:"Next",go:"Let's go!",skip:"Skip",wh:"Choose a nickname",ph:"Your nickname",why:"How others will see you",enter:"Let's Go",splash:"How well do you know the world?",splashSub:"Master flags, landmarks, and trivia.",start:"Discover",noAcc:"No account needed",guest:"Progress saved locally. Sign up later for Global Leaderboard."},fr:{next:"Suivant",go:"C'est parti !",skip:"Passer",wh:"Choisissez un pseudo",ph:"Votre pseudo",why:"Comment les autres vous verront",enter:"C'est parti",splash:"Que savez-vous du monde ?",splashSub:"Maîtrisez drapeaux et trivia.",start:"Découvrir",noAcc:"Aucun compte nécessaire",guest:"Progression sauvegardée localement."},ar:{next:"التالي",go:"!هيا بنا",skip:"تخطي",wh:"اختر اسماً",ph:"اسمك",why:"كيف سيراك الآخرون",enter:"هيا بنا",splash:"كم تعرف عن العالم؟",splashSub:"أتقن الأعلام والمعرفة.",start:"اكتشف",noAcc:"لا حاجة لحساب",guest:"تقدمك محفوظ محلياً."},es:{next:"Siguiente",go:"¡Vamos!",skip:"Saltar",wh:"Elige un apodo",ph:"Tu apodo",why:"Cómo te verán los demás",enter:"¡Vamos!",splash:"¿Cuánto sabes del mundo?",splashSub:"Domina banderas y trivia.",start:"Descubrir",noAcc:"Sin cuenta necesaria",guest:"Progreso guardado localmente."}};
var LANGS=[{c:"en",n:"English"},{c:"fr",n:"Français"},{c:"es",n:"Español"},{c:"ar",n:"العربية"}];
var T={en:{brand:"GeoDojo",mastered:"Mastered",fQ:"Flag Blitz",cQ:"Capital Drill",conf:"Look-Alikes",triv:"Trivia",prog:"Stats",back:"Back",exit:"Exit",prev:"Prev",next:"Next",nxtQ:"Next",ok:"Correct!",fire:"On fire!",un:"Amazing!",nope:"Not quite",ans:"Answer:",wh:"Which country?",isCap:"Capital of...",jour:"Your Progress",co:"Country",ca:"Capital",cn:"Region",mn:"Meaning",cfsd:"Confused with",dy:"Fun fact",ty:"Type country name",ph:"Type...",toNext:"to next belt",smart:"Type mode",share:"Share Results",timeUp:"Time!",pts:"pts",only:"Only",toBelt:"to",sess:"Complete",again:"Play Again",home:"Home",selectRegion:"Region",privacy:"Privacy",terms:"Terms",train:"Study Mode"},fr:{brand:"GeoDojo",mastered:"Maîtrisés",fQ:"Blitz drapeaux",cQ:"Drill capitales",conf:"Similaires",triv:"Trivia",prog:"Stats",back:"Retour",exit:"Quitter",prev:"Préc",next:"Suiv",nxtQ:"Suivant",ok:"Correct !",fire:"En feu !",un:"Incroyable !",nope:"Pas tout à fait",ans:"Réponse :",wh:"Quel pays ?",isCap:"Capitale de...",jour:"Votre progression",co:"Pays",ca:"Capitale",cn:"Région",mn:"Signification",cfsd:"Confondu avec",dy:"Le saviez-vous",ty:"Tapez le nom",ph:"Tapez...",toNext:"prochaine ceinture",smart:"Mode frappe",share:"Partager",timeUp:"Temps !",pts:"pts",only:"Plus que",toBelt:"vers",sess:"Terminée",again:"Rejouer",home:"Accueil",selectRegion:"Région",privacy:"Confidentialité",terms:"Conditions",train:"Mode étude"},ar:{brand:"جيو دوجو",mastered:"متقنة",fQ:"بليتز الأعلام",cQ:"تدريب العواصم",conf:"متشابهات",triv:"تحدي المعرفة",prog:"إحصائيات",back:"رجوع",exit:"خروج",prev:"السابق",next:"التالي",nxtQ:"التالي",ok:"صحيح!",fire:"ممتاز!",un:"رائع!",nope:"ليس تماماً",ans:"الإجابة:",wh:"أي بلد؟",isCap:"عاصمة...",jour:"تقدمك",co:"البلد",ca:"العاصمة",cn:"المنطقة",mn:"المعنى",cfsd:"يخلط مع",dy:"هل تعلم",ty:"اكتب اسم البلد",ph:"اكتب...",toNext:"للحزام التالي",smart:"وضع الكتابة",share:"شارك",timeUp:"الوقت!",pts:"نقاط",only:"فقط",toBelt:"إلى",sess:"انتهت",again:"العب مجدداً",home:"الرئيسية",selectRegion:"المنطقة",privacy:"الخصوصية",terms:"الشروط",train:"وضع الدراسة"},es:{brand:"GeoDojo",mastered:"Dominados",fQ:"Blitz banderas",cQ:"Drill capitales",conf:"Parecidos",triv:"Trivia",prog:"Stats",back:"Atrás",exit:"Salir",prev:"Ant",next:"Sig",nxtQ:"Siguiente",ok:"¡Correcto!",fire:"¡En racha!",un:"¡Increíble!",nope:"No exactamente",ans:"Respuesta:",wh:"¿Qué país?",isCap:"Capital de...",jour:"Tu progreso",co:"País",ca:"Capital",cn:"Región",mn:"Significado",cfsd:"Confundir con",dy:"Sabías que",ty:"Escribe el nombre",ph:"Escribe...",toNext:"siguiente cinturón",smart:"Modo escritura",share:"Compartir",timeUp:"¡Tiempo!",pts:"pts",only:"Solo",toBelt:"para",sess:"Completa",again:"Jugar de nuevo",home:"Inicio",selectRegion:"Región",privacy:"Privacidad",terms:"Términos",train:"Modo estudio"}};
var CM={en:{All:"All",Africa:"Africa",Europe:"Europe",Asia:"Asia","North America":"Americas","South America":"S. America",Oceania:"Oceania"},fr:{All:"Tous",Africa:"Afrique",Europe:"Europe",Asia:"Asie","North America":"Amériques","South America":"Am. Sud",Oceania:"Océanie"},ar:{All:"الكل",Africa:"أفريقيا",Europe:"أوروبا",Asia:"آسيا","North America":"الأمريكيتين","South America":"أمريكا ج.",Oceania:"أوقيانوسيا"},es:{All:"Todos",Africa:"África",Europe:"Europa",Asia:"Asia","North America":"Américas","South America":"Am. Sur",Oceania:"Oceanía"}};
var Logo=function(p){return <img src="/icon-192.png" alt="GeoDojo" style={{width:p.size||36,height:p.size||36,borderRadius:(p.size||36)*.25,flexShrink:0,objectFit:"contain"}} />;};
function usePreloader(urls){useEffect(function(){urls.forEach(function(u){if(u){var img=new Image();img.src=u;}});},[urls.join(",")]);}
export default function App(){
var s0=function(k,d){try{var v=localStorage.getItem(k);return v?JSON.parse(v):d;}catch(e){return d;}};
var s1=function(k,d){try{return localStorage.getItem(k)||d;}catch(e){return d;}};
var[ob,sOb]=useState(-1),[lang,sl]=useState("en"),[uN,sUN]=useState(""),[ni,sNI]=useState("");
var[dark,setDark]=useState(function(){return s1("geodojo-dark","0")==="1";});
var[langOpen,setLangOpen]=useState(false);
var[scr,sS]=useState("home"),[ct,sC]=useState("All"),[md,sM]=useState(null),[q,sQ]=useState(null),[op,sO]=useState([]);
var[se,sSe]=useState(null),[ok_,sOk]=useState(null),[sc,sSc]=useState(0),[to,sTo]=useState(0),[sk,sSk]=useState(0),[bk,sBk]=useState(0);
var[li,sLi]=useState(0),[ms,sMs]=useState({}),[dy,sDy]=useState(0);
var[fc,sFc]=useState(0),[iT,sIT]=useState(false),[tv,sTV]=useState(""),[ts,sTS]=useState(false),[rn,sRn]=useState(0);
var[timer,setTimer]=useState(10),[timerActive,setTimerActive]=useState(false),[sessionResults,setSessionResults]=useState([]),[pts,setPts]=useState(0);
var[pb,setPb]=useState(function(){return s0("geodojo-pb",{});});
var[isNewPb,setIsNewPb]=useState(false);
var[dayStreak,setDayStreak]=useState(function(){var d=s0("geodojo-streak",{});var today=new Date().toDateString();if(d.last===today)return d.count||0;var yest=new Date(Date.now()-86400000).toDateString();if(d.last===yest)return d.count||0;return 0;});
var[pid,sPid]=useState(function(){return s1("geodojo-pid",null);});
var[cloudLb,setCloudLb]=useState([]);
var[userCountry,setUserCountry]=useState(function(){return s1("geodojo-country","Morocco");});
var[chalCode,setChalCode]=useState(""),[chalData,setChalData]=useState(null),[chalMode,setChalMode]=useState(false),[joinCode,setJoinCode]=useState("");
var[userEmail,setUserEmail]=useState(function(){return s1("geodojo-email","");});
var aS=useRef(Date.now());var timerRef=useRef(null);
var t=T[lang]||T.en;var ot=OT[lang]||OT.en;var rtl=lang==="ar";
var GC=function(d){return d?"glass-dark":"glass";};
var pl=useMemo(function(){return ct==="All"?D:D.filter(function(c){return c.z===ct;});},[ct]);
var gm=function(i){var m=ms[i];return !m||!m.s?0:Math.round((m.c/m.s)*100);};
var mc=useMemo(function(){return D.filter(function(c){return gm(c.i)>=80;}).length;},[ms]);
var belt=gB(mc);var nextBelt=nxB(mc);
var N=function(c){return c.n[lang]||c.n.en;};var Ca=function(c){return c.c[lang]||c.c.en;};
var Mg=function(c){return c.m[lang]||c.m.en;};var Ff=function(c){return c.f[lang]||c.f.en;};
var cl=function(k){return (CM[lang]||CM.en)[k]||k;};
var preloadUrls=useMemo(function(){if(!q||q.trivia)return [];return shuffle(pl).slice(0,3).map(function(c){return FL(c.i);});},[q,pl]);
usePreloader(preloadUrls);
var acc=mc>0?Math.round((Object.values(ms).filter(function(m){return m.s>0;}).reduce(function(a,m){return a+m.c;},0)/(Object.values(ms).filter(function(m){return m.s>0;}).reduce(function(a,m){return a+m.s;},0)||1))*100):0;
var motiv=mc===0?(lang==="fr"?"Votre voyage commence.":lang==="ar"?"رحلتك تبدأ هنا.":lang==="es"?"Tu viaje comienza.":"Your journey begins."):mc<20?(lang==="fr"?"Continuez comme ça !":lang==="ar"?"استمر هكذا!":lang==="es"?"¡Sigue así!":"Keep it up!"):mc<60?(lang==="fr"?"Vous progressez vite !":lang==="ar"?"تقدمك سريع!":lang==="es"?"¡Progresas rápido!":"You're improving fast!"):mc<120?(lang==="fr"?"Impressionnant !":lang==="ar"?"مثير للإعجاب!":lang==="es"?"¡Impresionante!":"Impressive!"):(lang==="fr"?"Incroyable maîtrise !":lang==="ar"?"إتقان مذهل!":lang==="es"?"¡Dominio increíble!":"Incredible mastery!");
// ═══ CORE LOGIC ═══
var gen=useCallback(function(m,p){
  if(m==="trivia"){var tq=TRIVIA[~~(Math.random()*TRIVIA.length)];var sh=shuffle([0,1,2,3]);sQ({trivia:true,q:tq.q[lang]||tq.q.en,opts:sh.map(function(i){return (tq.o[lang]||tq.o.en)[i];}),ans:sh.indexOf(tq.a)});sO([]);sSe(null);sOk(null);sTV("");sTS(false);aS.current=Date.now();return;}
  if(p.length<4)return;var r=rn+1;sRn(r);
  var du=p.filter(function(c){var m2=ms[c.i];return m2&&m2.nd&&m2.nd<=r;});
  var wk=p.filter(function(c){var m2=ms[c.i];return m2&&m2.w>0&&m2.w>=m2.c;});
  var tg=du.length>0?du[~~(Math.random()*du.length)]:wk.length>0&&Math.random()<.4?wk[~~(Math.random()*wk.length)]:p[~~(Math.random()*p.length)];
  var cf=tg.x.map(function(i){return D.find(function(c){return c.i===i;});}).filter(Boolean);
  sQ(tg);sO(shuffle([tg].concat(cf).concat(shuffle(p.filter(function(c){return c.i!==tg.i&&!tg.x.includes(c.i);})))).slice(0,4));
  sSe(null);sOk(null);sTV("");sTS(false);aS.current=Date.now();
},[ms,rn,lang]);
var rec=function(ok){if(!q||q.trivia)return;sMs(function(prev){var e=prev[q.i]||{c:0,w:0,s:0,nd:0,iv:0};if(ok)return Object.assign({},prev,Object.fromEntries([[q.i,{c:e.c+1,w:e.w,s:e.s+1,nd:0,iv:0}]]));var x=Math.min(e.iv||0,SR.length-1);return Object.assign({},prev,Object.fromEntries([[q.i,{c:e.c,w:e.w+1,s:e.s+1,nd:rn+SR[x],iv:(e.iv||0)+1}]]));});};
var calcPts=function(ok,el){return ok?Math.round((100+Math.max(0,Math.round((10-el/1000)*10)))*(1+Math.min(sk,10)*0.1)):0;};
var chkT=function(){if(ts)return;sTS(true);setTimerActive(false);var v=tv.trim();if(!v){sOk(false);sSe({i:"_"});rec(false);hNo();sTo(function(p){return p+1;});sDy(function(p){return p+1;});setSessionResults(function(r){return r.concat([false]);});sSk(0);sFc(0);return;}var res=fuse.search(v);var matched=res.length>0&&res[0].item.iso===q.i&&res[0].score<0.4;var exact=[q.n.en,q.n.fr,q.n.ar,q.n.es].some(function(n){return n&&n.toLowerCase()===v.toLowerCase();});var ok=matched||exact;var el=Date.now()-aS.current;var p=calcPts(ok,el);sOk(ok);sSe({i:ok?q.i:"_"});rec(ok);sTo(function(x){return x+1;});sDy(function(x){return x+1;});setSessionResults(function(r){return r.concat([ok]);});setPts(function(x){return x+p;});if(ok){hOk();sSc(function(x){return x+1;});sSk(function(x){var n=x+1;if(n>bk)sBk(n);return n;});sFc(function(x){return x+1;});}else{hNo();sSk(0);sFc(0);}};
var answer=function(o,idx){if(se)return;setTimerActive(false);var el=Date.now()-aS.current;if(q.trivia){var ok=idx===q.ans;var p=calcPts(ok,el);sOk(ok);sSe({i:ok?"ok":"_"});sTo(function(x){return x+1;});sDy(function(x){return x+1;});setSessionResults(function(r){return r.concat([ok]);});setPts(function(x){return x+p;});if(ok){hOk();sSc(function(x){return x+1;});sSk(function(x){var n=x+1;if(n>bk)sBk(n);return n;});}else{hNo();sSk(0);}return;}sSe(o);var ok2=o.i===q.i;var p2=calcPts(ok2,el);sOk(ok2);rec(ok2);sTo(function(x){return x+1;});sDy(function(x){return x+1;});setSessionResults(function(r){return r.concat([ok2]);});setPts(function(x){return x+p2;});if(ok2){hOk();sSc(function(x){return x+1;});sSk(function(x){var n=x+1;if(n>bk)sBk(n);return n;});if(el<2000)sFc(function(x){return x+1;});else sFc(0);}else{hNo();sSk(0);sFc(0);}};
var nxt=function(){gen(md,pl);setTimer(sk>=5?7:10);setTimerActive(true);};
var start=function(m){sM(m);sSc(0);sTo(0);sSk(0);sFc(0);sIT(false);sRn(0);setPts(0);setTimer(10);setTimerActive(true);setSessionResults([]);gen(m,pl);sS("quiz");};
var endSession=function(){setTimerActive(false);sS("end");var mode=md||"flags";var prev=pb[mode]||0;if(pts>prev){setPb(function(p){var n=Object.assign({},p);n[mode]=pts;localStorage.setItem("geodojo-pb",JSON.stringify(n));return n;});setIsNewPb(true);}else setIsNewPb(false);try{var today=new Date().toDateString();var d=s0("geodojo-streak",{});var yest=new Date(Date.now()-86400000).toDateString();var count=1;if(d.last===today)count=d.count||1;else if(d.last===yest)count=(d.count||0)+1;localStorage.setItem("geodojo-streak",JSON.stringify({last:today,count:count}));setDayStreak(count);}catch(e){}if(pid){submitScore(pid,pts,sc,to,mode,sk,bN(belt,lang)).then(function(){getLeaderboard(50).then(function(d){setCloudLb(d||[]);});}).catch(function(){});if(chalMode&&chalData){submitChallengeResult(chalData.id,pid,pts,sc,to).catch(function(){});setChalMode(false);}}};
var shareResults=function(){var msgs={en:function(b,s,tt,p,sk2){return "I just scored "+p+" points on GeoDojo!\n"+b+" - "+s+"/"+tt+(sk2>=3?" - "+sk2+"x streak":"")+"\n\nCan you beat me?\nhttps://geodojo.app";},fr:function(b,s,tt,p,sk2){return "Je viens de marquer "+p+" points sur GeoDojo !\n"+b+" - "+s+"/"+tt+(sk2>=3?" - "+sk2+"x serie":"")+"\n\nDefie-moi :\nhttps://geodojo.app";},ar:function(b,s,tt,p,sk2){return "سجلت "+p+" نقطة على GeoDojo!\n"+b+" - "+s+"/"+tt+(sk2>=3?" - سلسلة "+sk2+"x":"")+"\n\nتحداني:\nhttps://geodojo.app";},es:function(b,s,tt,p,sk2){return "Acabo de marcar "+p+" puntos en GeoDojo!\n"+b+" - "+s+"/"+tt+(sk2>=3?" - "+sk2+"x racha":"")+"\n\nDesafiame:\nhttps://geodojo.app";}};var fmt=msgs[lang]||msgs.en;var txt=fmt(bN(belt,lang),sc,to,pts,sk);if(navigator.share)navigator.share({text:txt}).catch(function(){});else if(navigator.clipboard)navigator.clipboard.writeText(txt).then(function(){alert("Copied!");}).catch(function(){});};
var changeLang=function(c){sl(c);setLangOpen(false);};
// ═══ ALL EFFECTS ═══
useEffect(function(){getLeaderboard(50).then(function(d){setCloudLb(d||[]);}).catch(function(){});var sub=subscribeToScores(function(){getLeaderboard(50).then(function(d){setCloudLb(d||[]);}).catch(function(){});});return function(){supabase.removeChannel(sub);};},[]);
useEffect(function(){try{var s=localStorage.getItem("geodojo-v5");if(s){var d=JSON.parse(s);if(d.ms)sMs(d.ms);if(d.bk)sBk(d.bk);if(d.dy)sDy(d.dy);if(d.lang){sl(d.lang);;sOb(5);}if(d.uN)sUN(d.uN);}}catch(e){}},[]);
useEffect(function(){localStorage.setItem("geodojo-dark",dark?"1":"0");document.body.style.background=dark?"#0D0D0D":"#FFFFFF";document.body.style.color=dark?"#E0E0E8":"#1A1A2E";},[dark]);
useEffect(function(){if(pid&&lang){updateProfile(pid,{username:uN||"Anon",belt:bN(belt,lang),mastered:mc,country:userCountry}).catch(function(){});}},[mc,belt,lang]);
useEffect(function(){if(lang)localStorage.setItem("geodojo-v5",JSON.stringify({ms:ms,bk:bk,lang:lang,uN:uN,dy:dy}));},[ms,bk,lang,uN,dy]);
useEffect(function(){if(ob===5&&!pid&&lang){var nm=uN||"Anon";createProfile(nm,userCountry).then(function(p){if(p){sPid(p.id);localStorage.setItem("geodojo-pid",p.id);}}).catch(function(){});}},[ob,pid,lang]);
useEffect(function(){if(timerActive&&timer>0){timerRef.current=setTimeout(function(){setTimer(function(t2){return t2-1;});},1000);}if(timerActive&&timer<=0&&!se&&q){sOk(false);sSe({i:"_"});rec(false);hNo();sTo(function(p){return p+1;});sDy(function(p){return p+1;});setSessionResults(function(r){return r.concat([false]);});sSk(0);sFc(0);setTimeout(function(){gen(md,pl);setTimer(10);},1500);}if(timerActive&&timer<=3&&timer>0)heartbeat();return function(){clearTimeout(timerRef.current);};},[timer,timerActive]);
useEffect(function(){if(fc>=3&&!iT)sIT(true);},[fc]);
useEffect(function(){if(ok_===true&&se){var tm=setTimeout(function(){if(to>=20)endSession();else nxt();},1500);return function(){clearTimeout(tm);};}},[ok_,se]);
useEffect(function(){var hash=window.location.hash;if(hash.startsWith("#/u/"))sS("profile");},[]);
// ═══ BUTTON ═══
var B=function(props){return <button onClick={props.onClick} disabled={props.disabled} style={{padding:props.big?"16px 20px":"12px 16px",borderRadius:$.r,width:props.full?"100%":"auto",fontSize:props.big?17:14,fontWeight:800,textAlign:"center",background:props.outline?"transparent":(props.c||$.pri),color:props.outline?dk(dark,$.sub,"#8888AA"):"#FFF",border:props.outline?"2px solid "+dk(dark,$.bdr,"#2A2A3E"):"none",boxShadow:props.outline?"none":"0 4px 0 0 "+(props.d||$.priD),opacity:props.disabled?.4:1,transition:"all .1s"}}>{props.children}</button>;};
// ═══ ONBOARDING ═══
if(ob<5){
if(ob===-1)return(<div style={{minHeight:"100vh",background:dk(dark,"#FFF","#0D0D0D"),display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{textAlign:"center",padding:"0 32px",maxWidth:400}}>
  <div style={{display:"flex",justifyContent:"center",gap:6,marginBottom:28}}>{LANGS.map(function(l){return <button key={l.c} onClick={function(){sl(l.c);}} style={{padding:"6px 14px",borderRadius:10,fontSize:12,fontWeight:700,background:lang===l.c?LCOL[l.c]:dk(dark,"#F4F6F8","#1A1A2E"),color:lang===l.c?"#FFF":dk(dark,"#9494B0","#666680"),border:"none"}}>{l.n}</button>;})}</div>
  <Logo size={100} /><div style={{height:20}} />
  <h1 style={{fontSize:28,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:8}}>{ot.splash}</h1>
  <p style={{fontSize:14,color:dk(dark,$.sub,"#8888AA"),fontWeight:600,marginBottom:32,lineHeight:1.5}}>{ot.splashSub}</p>
  <B full big onClick={function(){sOb(0);}}>{ot.start}</B>
  <div style={{marginTop:14,fontSize:11,color:dk(dark,$.mu,"#666680")}}>{ot.noAcc}</div>
</div></div>);
if(ob>=0&&ob<=2){var vc=VCARDS[ob];return(<div style={{minHeight:"100vh",background:dk(dark,"#FFF","#0D0D0D"),display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{textAlign:"center",padding:"0 28px",maxWidth:400,width:"100%"}}>
  <div className={GC(dark)} style={{borderRadius:22,padding:"32px 22px",marginBottom:24,minHeight:200,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",background:dk(dark,vc.bg+"AA",vc.color+"12")}}>
    <div style={{width:52,height:52,borderRadius:15,background:vc.color,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:16,boxShadow:"0 4px 0 0 "+vc.color+"80"}}><div style={{width:18,height:18,borderRadius:9,background:"rgba(255,255,255,.3)"}} /></div>
    <h2 style={{fontSize:22,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:6}}>{vc.title[lang]||vc.title.en}</h2>
    <p style={{fontSize:13,color:dk(dark,$.sub,"#8888AA"),lineHeight:1.5}}>{vc.desc[lang]||vc.desc.en}</p>
  </div>
  <div style={{display:"flex",justifyContent:"center",gap:8,marginBottom:20}}>{VCARDS.map(function(_,i){return <div key={i} style={{width:i===ob?20:8,height:8,borderRadius:4,background:i===ob?vc.color:dk(dark,"#E8ECF0","#2A2A3E")}} />;})}</div>
  <B full onClick={function(){sOb(ob>=2?3:ob+1);}} c={vc.color} d={vc.color+"CC"}>{ob<2?ot.next:ot.go}</B>
  {ob<2&&<button onClick={function(){sOb(3);}} style={{marginTop:10,color:dk(dark,$.mu,"#666680"),fontSize:12,fontWeight:600,padding:6}}>{ot.skip}</button>}
</div></div>);}
if(ob>=3)return(<div style={{minHeight:"100vh",background:dk(dark,"#FFF","#0D0D0D"),display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{textAlign:"center",padding:"0 28px",maxWidth:380,width:"100%",direction:rtl?"rtl":"ltr"}}>
  <div style={{width:48,height:48,borderRadius:14,background:dk(dark,$.priL,"#2A1A1A"),display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px"}}><div style={{width:16,height:16,borderRadius:8,background:$.pri}} /></div>
  <h2 style={{fontSize:20,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:4}}>{ot.wh}</h2>
  <p style={{fontSize:11,color:dk(dark,$.mu,"#666680"),marginBottom:20}}>{ot.why}</p>
  <input value={ni} onChange={function(e){sNI(e.target.value);}} onKeyDown={function(e){if(e.key==="Enter"){sUN(ni.trim()||"Explorer");sOb(5);}}} placeholder={ot.ph} autoFocus style={{width:"100%",padding:"12px 16px",borderRadius:$.r,border:"2px solid "+(ni?$.pri:dk(dark,$.bdr,"#2A2A3E")),background:dk(dark,"#FFF","#141420"),fontSize:15,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8"),outline:"none",textAlign:rtl?"right":"center"}} />
  <select value={userCountry} onChange={function(e){setUserCountry(e.target.value);}} style={{width:"100%",padding:"11px 16px",borderRadius:$.r,border:"2px solid "+dk(dark,$.bdr,"#2A2A3E"),background:dk(dark,"#FFF","#141420"),fontSize:13,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8"),marginTop:8,outline:"none"}}>{ALL_COUNTRIES.map(function(c){return <option key={c} value={c}>{c}</option>;})}</select>
  <div style={{marginTop:12}}><B full onClick={function(){sUN(ni.trim()||"Explorer");sOb(5);localStorage.setItem("geodojo-country",userCountry);}}>{ot.enter}</B></div>
  <div style={{marginTop:10,fontSize:10,color:dk(dark,$.mu,"#666680"),fontStyle:"italic"}}>{ot.guest}</div>
</div></div>);
}
// ═══ MAIN RETURN ═══
return(<div style={{minHeight:"100vh",background:dk(dark,"#FFF","#0D0D0D"),color:dk(dark,$.ink,"#E0E0E8"),direction:rtl?"rtl":"ltr"}}><div style={{maxWidth:440,margin:"0 auto",padding:"0 16px 40px"}}>
{/* TOP BAR */}
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingTop:10,marginBottom:6}}>
  <div style={{display:"flex",alignItems:"center",gap:6,cursor:"pointer"}} onClick={function(){sS("home");}}>
    <Logo size={28} /><span style={{fontSize:14,fontWeight:800,color:dk(dark,$.ink,"#F0F0F8")}}>GeoDojo</span>
    {mc>0&&<div style={{display:"flex",alignItems:"center",gap:3,padding:"2px 8px",background:belt.color+"15",borderRadius:8}}><div style={{width:7,height:7,borderRadius:4,background:belt.color}} /><span style={{fontSize:9,fontWeight:700,color:belt.color}}>{bN(belt,lang)}</span></div>}
  </div>
  <div style={{display:"flex",alignItems:"center",gap:3,position:"relative"}}>
    <button onClick={function(){sS(scr==="profile"?"home":"profile");}} style={{width:28,height:28,borderRadius:8,background:dk(dark,$.faint,"#1A1A2E"),display:"flex",alignItems:"center",justifyContent:"center",border:"none"}}><div style={{width:14,height:14,borderRadius:7,background:$.pri,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:7,fontWeight:800,color:"#FFF"}}>{(uN||"?")[0].toUpperCase()}</span></div></button>
    <button onClick={function(){setDark(!dark);}} style={{width:28,height:28,borderRadius:8,background:dk(dark,$.faint,"#1A1A2E"),display:"flex",alignItems:"center",justifyContent:"center",border:"none",fontSize:12}}>{dark?"\u2600":"\u263D"}</button>
    <button onClick={function(){setLangOpen(!langOpen);}} style={{padding:"3px 8px",borderRadius:6,background:dk(dark,$.faint,"#1A1A2E"),fontSize:10,fontWeight:700,color:dk(dark,$.sub,"#8888AA"),border:"none"}}>{lang.toUpperCase()}</button>
    {langOpen&&<div style={{position:"absolute",top:32,right:0,zIndex:20,borderRadius:12,padding:4,display:"flex",flexDirection:"column",gap:2,minWidth:100}} className={GC(dark)}>
      {LANGS.map(function(l){return <button key={l.c} onClick={function(){changeLang(l.c);}} style={{padding:"8px 12px",borderRadius:8,fontSize:12,fontWeight:700,textAlign:"left",color:lang===l.c?"#FFF":dk(dark,$.ink,"#E0E0E8"),background:lang===l.c?LCOL[l.c]:"transparent"}}>{l.n}</button>;})}</div>}
  </div>
</div>
{/* HOME */}
{scr==="home"&&(<div className="fadeUp">
  <div className={GC(dark)} style={{borderRadius:18,padding:14,marginBottom:10,textAlign:"center",position:"relative",overflow:"hidden"}}>
    <div style={{position:"absolute",top:0,left:0,right:0,height:3,background:"linear-gradient(90deg,"+belt.color+","+(nextBelt?nextBelt.color:belt.color)+")"}} />
    <div style={{fontSize:28,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8")}}>{mc}<span style={{fontSize:12,color:dk(dark,$.mu,"#666680")}}>/{D.length}</span></div>
    <div style={{fontSize:9,fontWeight:700,color:dk(dark,$.mu,"#666680"),textTransform:"uppercase",letterSpacing:1.5}}>{t.mastered}</div>
    {dayStreak>0&&<div style={{display:"inline-flex",alignItems:"center",gap:3,marginTop:4,padding:"3px 10px",background:dk(dark,"#FFF3E0","#2D2000"),borderRadius:8}}><span style={{fontSize:11}}>🔥</span><span style={{fontSize:10,fontWeight:700,color:$.gld}}>{dayStreak}d</span></div>}
    {nextBelt&&<div style={{marginTop:6}}><div style={{width:"100%",height:6,background:dk(dark,"#F4F6F8","#1A1A2E"),borderRadius:3,overflow:"hidden"}}><div style={{width:Math.min((mc/nextBelt.min)*100,100)+"%",height:"100%",background:"linear-gradient(90deg,"+belt.color+","+nextBelt.color+")",borderRadius:3}} /></div><div style={{fontSize:9,fontStyle:"italic",color:$.pri,marginTop:3}}>{motiv}</div></div>}
  </div>
  <div style={{display:"flex",justifyContent:"center",gap:10,marginBottom:10,fontSize:11,fontWeight:600,color:dk(dark,$.sub,"#8888AA")}}>
    <span><span style={{color:$.pri,fontWeight:800}}>{dy}</span> streak</span><span style={{color:dk(dark,$.bdr,"#2A2A3E")}}>-</span><span><span style={{color:$.gld,fontWeight:800}}>{bk}</span> best</span><span style={{color:dk(dark,$.bdr,"#2A2A3E")}}>-</span><span><span style={{color:$.ok,fontWeight:800}}>{acc}%</span> acc</span>
  </div>
  <div style={{display:"flex",gap:4,flexWrap:"wrap",justifyContent:"center",marginBottom:10}}>{CONTS.map(function(k){var co=CC[k];return <button key={k} onClick={function(){sC(k);}} style={{padding:"5px 10px",borderRadius:8,fontSize:10,fontWeight:700,background:ct===k?co:dk(dark,"#FFF","#141420"),color:ct===k?"#FFF":dk(dark,$.sub,"#8888AA"),border:"2px solid "+(ct===k?co:dk(dark,$.bdr,"#2A2A3E"))}}>{cl(k)}</button>;})}</div>
  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:10}}>
    {[[t.fQ,$.pri,$.priD,"flags"],[t.cQ,$.blu,$.bluD,"capitals"],[t.conf,$.pur,$.purD,"confusers"],[t.triv,$.gld,$.gldD,"trivia"]].map(function(item,i){return <button key={i} onClick={function(){start(item[3]);}} className={GC(dark)} style={{padding:"18px 12px",borderRadius:14,textAlign:"center"}}><div style={{width:36,height:36,borderRadius:10,background:item[1],display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 8px",boxShadow:"0 3px 0 0 "+item[2]}}><div style={{width:12,height:12,borderRadius:6,background:"rgba(255,255,255,.3)"}} /></div><div style={{fontSize:13,fontWeight:800,color:dk(dark,$.ink,"#F0F0F8")}}>{item[0]}</div></button>;})}
  </div>
  <button onClick={function(){sLi(~~(Math.random()*pl.length));sS("learn");}} className={GC(dark)} style={{width:"100%",padding:10,borderRadius:12,fontSize:12,fontWeight:700,color:dk(dark,$.sub,"#8888AA"),marginBottom:10}}>{t.train}</button>
  <div className={GC(dark)} style={{borderRadius:14,padding:12,marginBottom:8}}>
    <div style={{fontSize:12,fontWeight:800,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:6}}>Global Ranking</div>
    {cloudLb.slice(0,3).map(function(e,i){return <div key={e.id||i} style={{display:"flex",alignItems:"center",gap:6,marginBottom:4}}><div style={{width:20,height:20,borderRadius:6,background:i===0?$.gld:i===1?"#94A3B8":"#B45309",display:"flex",alignItems:"center",justifyContent:"center",color:"#FFF",fontSize:8,fontWeight:800}}>{i+1}</div><div style={{flex:1,fontSize:11,fontWeight:600,color:dk(dark,$.ink,"#E0E0E8")}}>{e.username}{e.id===pid?" (you)":""}</div><div style={{fontSize:11,fontWeight:800,color:$.pri}}>{e.total_pts}</div></div>;})}
    {cloudLb.length===0&&<div style={{fontSize:11,color:dk(dark,$.mu,"#666680"),textAlign:"center",padding:6}}>Play to join!</div>}
    <div style={{display:"flex",gap:4,marginTop:6}}><button onClick={function(){if(userEmail)sS("leaderboard");else sS("signup");}} style={{flex:1,padding:8,borderRadius:10,background:$.pri,color:"#FFF",fontSize:11,fontWeight:700,border:"none",boxShadow:"0 3px 0 0 "+$.priD}}>Full Ranking</button><button onClick={function(){var txt="Join me on GeoDojo!\nhttps://geodojo.app";if(navigator.share)navigator.share({text:txt}).catch(function(){});else if(navigator.clipboard){navigator.clipboard.writeText(txt);alert("Copied!");}}} style={{flex:1,padding:8,borderRadius:10,background:$.gld,color:"#FFF",fontSize:11,fontWeight:700,border:"none",boxShadow:"0 3px 0 0 "+$.gldD}}>Invite</button></div>
  </div>
  <div style={{textAlign:"center",padding:"10px 0",display:"flex",justifyContent:"center",gap:14}}><a href="/privacy.html" target="_blank" style={{fontSize:9,color:dk(dark,$.mu,"#666680"),textDecoration:"none"}}>{t.privacy}</a><a href="/terms.html" target="_blank" style={{fontSize:9,color:dk(dark,$.mu,"#666680"),textDecoration:"none"}}>{t.terms}</a></div>
</div>)}
{/* LEARN */}
{scr==="learn"&&(function(){var c=pl[li];if(!c)return null;var cf=c.x.map(function(i){return D.find(function(x){return x.i===i;});}).filter(Boolean);return <div className="fadeUp"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><button onClick={function(){sS("home");}} style={{color:$.pri,fontSize:12,fontWeight:700}}>{rtl?t.back+" \u2190":"\u2190 "+t.back}</button><span style={{fontSize:10,color:dk(dark,$.mu,"#666680"),fontWeight:700}}>{li+1}/{pl.length}</span></div><div className={GC(dark)} style={{borderRadius:16,padding:14,marginBottom:8}}><div style={{display:"flex",justifyContent:"center",marginBottom:10}}><img src={FL(c.i)} alt={N(c)} width={200} height={134} style={{borderRadius:10,border:"2px solid "+dk(dark,$.bdr,"#2A2A3E"),objectFit:"cover"}} onError={function(e){e.target.style.display="none";}} /></div>{[[t.co,N(c),dk(dark,$.ink,"#F0F0F8"),800],[t.ca,Ca(c),$.pri,700],[t.cn,cl(c.z),dk(dark,$.sub,"#8888AA"),600]].map(function(item,j){return <div key={j} style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:j<2?"1px solid "+dk(dark,$.faint,"#1A1A2E"):"none"}}><span style={{fontSize:9,fontWeight:700,color:dk(dark,$.mu,"#666680"),textTransform:"uppercase",letterSpacing:1}}>{item[0]}</span><span style={{fontSize:j===0?15:13,fontWeight:item[3],color:item[2]}}>{item[1]}</span></div>;})}<div style={{marginTop:8,padding:"8px 10px",background:dk(dark,$.priL+"88","#1A1020"),borderRadius:8,borderLeft:"3px solid "+$.pri}}><div style={{fontSize:8,fontWeight:700,color:$.pri,textTransform:"uppercase",letterSpacing:1}}>{t.dy}</div><div style={{fontSize:11,color:dk(dark,$.ink,"#C8C8E0"),lineHeight:1.5}}>{Ff(c)}</div></div>{cf.length>0&&<div style={{marginTop:6,padding:"8px 10px",background:dk(dark,$.redL+"88","#2A1010"),borderRadius:8,borderLeft:"3px solid "+$.red}}><div style={{fontSize:8,fontWeight:700,color:$.redD,textTransform:"uppercase",letterSpacing:1}}>{t.cfsd}</div><div style={{display:"flex",gap:4,flexWrap:"wrap",marginTop:3}}>{cf.map(function(f){return <div key={f.i} style={{display:"flex",alignItems:"center",gap:3}}><img src={FS(f.i)} alt="" width={22} height={15} style={{borderRadius:2,border:"1px solid "+dk(dark,$.bdr,"#2A2A3E")}} /><span style={{fontSize:10,color:dk(dark,$.ink,"#C8C8E0"),fontWeight:600}}>{N(f)}</span></div>;})}</div></div>}</div><div style={{display:"flex",gap:6}}><B outline full onClick={function(){sLi(Math.max(0,li-1));}} disabled={li===0}>{t.prev}</B><B full onClick={function(){sLi(Math.min(pl.length-1,li+1));}} disabled={li===pl.length-1}>{t.next}</B></div></div>;})()} 
{/* QUIZ */}
{scr==="quiz"&&q&&(<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}><button onClick={function(){endSession();}} style={{color:dk(dark,$.mu,"#666680"),fontSize:12,fontWeight:700}}>{rtl?t.exit+" \u2190":"\u2190 "+t.exit}</button><div style={{display:"flex",alignItems:"center",gap:4}}>{iT&&<span style={{fontSize:8,fontWeight:800,color:"#FFF",background:$.pur,padding:"2px 6px",borderRadius:4}}>{t.smart}</span>}{sk>=3&&<span style={{fontSize:12,fontWeight:900,color:$.gld}}>{sk}x</span>}<span style={{fontSize:10,fontWeight:700,color:dk(dark,$.mu,"#666680")}}>{to}/20</span><span style={{fontSize:16,fontWeight:900,color:$.pri}}>{pts}</span></div></div>
<div style={{width:"100%",height:8,background:dk(dark,$.bdr,"#1A1A2E"),borderRadius:4,marginBottom:2,overflow:"hidden"}}><div style={{width:(timer/(sk>=5?7:10))*100+"%",height:"100%",background:timer>5?$.pri:timer>2?$.gld:$.red,borderRadius:4,transition:"width 1s linear"}} /></div>
<div style={{textAlign:"center",fontSize:18,fontWeight:900,color:timer>5?$.pri:timer>2?$.gld:$.red,marginBottom:8}}>{timer}s</div>
<div key={(q.trivia?q.q:q.i)+to} className="fadeUp">{q.trivia?<div className={GC(dark)} style={{borderRadius:14,padding:"10px 12px",marginBottom:8,textAlign:"center",borderLeft:"4px solid "+$.gld}}><div style={{fontSize:14,fontWeight:800,color:dk(dark,$.ink,"#F0F0F8"),lineHeight:1.4}}>{q.q}</div></div>:md==="capitals"?<div style={{textAlign:"center",marginBottom:8}}><div style={{fontSize:22,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8")}}>{Ca(q)}</div><div style={{fontSize:11,color:dk(dark,$.mu,"#666680"),marginTop:2}}>{t.isCap}</div></div>:<div style={{display:"flex",flexDirection:"column",alignItems:"center",marginBottom:8}}><img src={FL(q.i)} alt="" width={220} height={148} style={{borderRadius:12,border:"2px solid "+dk(dark,$.bdr,"#2A2A3E"),objectFit:"cover"}} onError={function(e){e.target.style.display="none";}} /><div style={{fontSize:12,color:dk(dark,$.mu,"#666680"),marginTop:4}}>{iT&&!q.trivia?t.ty:t.wh}</div></div>}
{iT&&!se&&!q.trivia?<div style={{marginBottom:8}}><input value={tv} onChange={function(e){sTV(e.target.value);}} onKeyDown={function(e){if(e.key==="Enter")chkT();}} placeholder={t.ph} autoFocus style={{width:"100%",padding:"12px 14px",borderRadius:$.r,border:"2px solid "+$.pur,background:dk(dark,"#FFF","#141420"),fontSize:15,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8"),outline:"none",textAlign:rtl?"right":"left"}} /><div style={{marginTop:6}}><B full onClick={chkT} c={$.pur} d={$.purD}>GO</B></div></div>:<div style={{display:"flex",flexDirection:"column",gap:5,marginBottom:8}}>{(q.trivia?q.opts.map(function(o,i){return {label:o,idx:i};}):op.map(function(o,i){return {label:N(o),obj:o,idx:i};})).map(function(item){var dn=se!==null;var isC,wasC;if(q.trivia){isC=item.idx===q.ans;wasC=dn&&se.i==="_"&&item.idx!==q.ans;}else{isC=item.obj&&item.obj.i===q.i;wasC=se&&se.i===(item.obj||{}).i&&!isC;}var bg=dk(dark,"#FFF","#141420"),bd=dk(dark,$.bdr,"#2A2A3E"),cl2=dk(dark,$.ink,"#E0E0E8");if(dn){if(isC){bg=dk(dark,$.okL,"#0A2A1A");bd=$.ok;cl2=$.okD;}else if(wasC){bg=dk(dark,$.redL,"#2A0A0A");bd=$.red;cl2=$.redD;}else{cl2=dk(dark,$.mu,"#555568");}}return <button key={item.idx} onClick={function(){q.trivia?answer(null,item.idx):answer(item.obj);}} disabled={dn} style={{width:"100%",padding:"11px 12px",textAlign:rtl?"right":"left",display:"flex",alignItems:"center",gap:8,background:bg,border:"2px solid "+bd,borderRadius:$.r,color:cl2,fontSize:14,fontWeight:700,transition:"all .1s"}}><span style={{width:24,height:24,borderRadius:7,flexShrink:0,display:"flex",alignItems:"center",justifyContent:"center",background:dn&&isC?$.ok:dn&&wasC?$.red:dk(dark,$.faint,"#1A1A2E"),color:dn&&(isC||wasC)?"#FFF":dk(dark,$.mu,"#666680"),fontSize:10,fontWeight:800}}>{dn&&isC?"\u2713":dn&&wasC?"\u2717":["A","B","C","D"][item.idx]}</span>{item.label}</button>;})}</div>}
{se&&<div className="fadeUp"><div style={{padding:"10px 14px",background:ok_?dk(dark,$.okL,"#0A2A1A"):dk(dark,$.redL,"#2A0A0A"),borderRadius:$.r,marginBottom:6,borderLeft:"4px solid "+(ok_?$.ok:$.red)}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{fontSize:14,fontWeight:900,color:ok_?$.okD:$.redD}}>{ok_?(sk>=5?t.un:sk>=3?t.fire:t.ok):t.nope}</div>{ok_&&<div style={{display:"flex",alignItems:"center",gap:4}}>{md==="capitals"&&q&&<img src={FL(q.i)} alt="" width={28} height={19} style={{borderRadius:3,border:"1px solid "+dk(dark,$.bdr,"#2A2A3E")}} />}<span style={{fontSize:13,fontWeight:800,color:$.okD}}>+{calcPts(true,Date.now()-aS.current)}</span></div>}</div>{!ok_&&!q.trivia&&<div style={{marginTop:3}}><div style={{display:"flex",alignItems:"center",gap:6}}><img src={FL(q.i)} alt="" width={32} height={22} style={{borderRadius:3,border:"1px solid "+dk(dark,$.bdr,"#2A2A3E")}} /><span style={{fontSize:12,color:$.redD,fontWeight:600}}>{t.ans} {N(q)}{md==="capitals"?" ("+Ca(q)+")":""}</span></div>{se.i&&se.i!=="_"&&se.i!==q.i&&<div style={{display:"flex",alignItems:"center",gap:4,marginTop:4,padding:"4px 8px",background:dk(dark,$.faint,"#1A1A2E"),borderRadius:6}}><img src={FS(se.i)} alt="" width={22} height={15} style={{borderRadius:2}} /><span style={{fontSize:9,color:dk(dark,$.mu,"#666680")}}>vs</span><img src={FS(q.i)} alt="" width={22} height={15} style={{borderRadius:2}} /></div>}</div>}{!ok_&&q.trivia&&<div style={{fontSize:12,color:$.redD,fontWeight:600,marginTop:2}}>{t.ans} {q.opts[q.ans]}</div>}</div><div style={{display:"flex",gap:6}}><B outline full onClick={endSession}>{t.exit}</B><B full onClick={function(){if(to>=20)endSession();else nxt();}}>{to>=20?t.exit:t.nxtQ}</B></div></div>}
</div></div>)}
{/* END */}
{scr==="end"&&<div className="fadeUp" style={{paddingTop:16,textAlign:"center"}}><div style={{fontSize:48,fontWeight:900,color:$.pri}}>{pts}</div><div style={{fontSize:13,color:dk(dark,$.sub,"#8888AA"),marginBottom:6}}>{t.pts}</div>{isNewPb&&<div style={{display:"inline-flex",alignItems:"center",gap:4,padding:"6px 14px",background:dk(dark,$.gldL,"#2D2000"),border:"2px solid "+$.gld,borderRadius:10,marginBottom:8}}><span style={{fontSize:12,fontWeight:800,color:$.gldD}}>{lang==="fr"?"Nouveau record !":lang==="ar"?"رقم قياسي جديد!":lang==="es"?"Nuevo record!":"New Personal Best!"}</span></div>}<div style={{display:"flex",flexWrap:"wrap",justifyContent:"center",gap:3,marginBottom:10}}>{sessionResults.map(function(r,i){return <div key={i} style={{width:20,height:20,borderRadius:5,background:r?$.ok:$.red,fontSize:9,color:"#FFF",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:800}}>{r?"\u2713":"\u2717"}</div>;})}</div><div style={{fontSize:13,fontWeight:700,color:dk(dark,$.sub,"#8888AA"),marginBottom:14}}>{sc}/{to}</div>{nextBelt&&<div className={GC(dark)} style={{borderRadius:14,padding:12,marginBottom:12,textAlign:"left"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:12,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8")}}>{bN(belt,lang)}</span><span style={{fontSize:10,fontWeight:700,color:nextBelt.color}}>{bN(nextBelt,lang)}</span></div><div style={{width:"100%",height:8,background:dk(dark,$.faint,"#1A1A2E"),borderRadius:4,overflow:"hidden"}}><div style={{width:Math.min((mc/nextBelt.min)*100,100)+"%",height:"100%",background:"linear-gradient(90deg,"+belt.color+","+nextBelt.color+")",borderRadius:4}} /></div></div>}<div style={{display:"flex",flexDirection:"column",gap:6}}><B full onClick={shareResults} c={$.ok} d={$.okD}>{t.share}</B><button onClick={function(){start(md||"flags");}} style={{width:"100%",padding:"14px",borderRadius:$.r,fontSize:15,fontWeight:800,background:$.pri,color:"#FFF",border:"none",boxShadow:"0 4px 0 0 "+$.priD,animation:"glow 2s ease-in-out infinite"}}>{t.again}</button><B full outline onClick={function(){sS("home");}}>{t.home}</B></div></div>}
{/* SIGNUP */}
{scr==="signup"&&<div className="fadeUp" style={{paddingTop:20,textAlign:"center"}}><h2 style={{fontSize:20,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:6}}>Unlock Leaderboard</h2><p style={{fontSize:12,color:dk(dark,$.mu,"#666680"),marginBottom:16}}>Sign up to compete globally.</p><input value={userEmail} onChange={function(e){setUserEmail(e.target.value);}} placeholder="your@email.com" type="email" style={{width:"100%",padding:"13px 16px",borderRadius:$.r,border:"2px solid "+(userEmail.includes("@")?$.pri:dk(dark,$.bdr,"#2A2A3E")),background:dk(dark,"#FFF","#141420"),fontSize:15,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8"),outline:"none",textAlign:"center",marginBottom:10}} /><B full onClick={function(){if(userEmail.includes("@")){localStorage.setItem("geodojo-email",userEmail);sS("leaderboard");}}} disabled={!userEmail.includes("@")}>Continue</B><button onClick={function(){sS("home");}} style={{marginTop:8,color:dk(dark,$.mu,"#666680"),fontSize:11,fontWeight:600,padding:6}}>Maybe later</button></div>}
{/* LEADERBOARD */}
{scr==="leaderboard"&&<div className="fadeUp"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><button onClick={function(){sS("home");}} style={{color:$.pri,fontSize:12,fontWeight:700}}>{"\u2190 "+t.back}</button></div><h2 style={{fontSize:18,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:10}}>Global Leaderboard</h2>{cloudLb.length===0?<div style={{textAlign:"center",padding:20,color:dk(dark,$.mu,"#666680"),fontSize:12}}>Play to join!</div>:cloudLb.slice(0,50).map(function(e,i){return <div key={e.id||i} className={GC(dark)} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:12,marginBottom:4,borderColor:e.id===pid?$.pri:undefined,borderWidth:e.id===pid?2:undefined}}><div style={{width:24,height:24,borderRadius:7,background:i===0?$.gld:i===1?"#94A3B8":i===2?"#B45309":dk(dark,$.faint,"#1A1A2E"),display:"flex",alignItems:"center",justifyContent:"center",color:i<3?"#FFF":dk(dark,$.mu,"#666680"),fontSize:10,fontWeight:800}}>{e.rank||i+1}</div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8")}}>{e.username}{e.id===pid?" (you)":""}</div><div style={{fontSize:9,color:dk(dark,$.mu,"#666680")}}>{e.belt} - {e.country}</div></div><div style={{fontSize:14,fontWeight:800,color:$.pri}}>{e.total_pts}</div></div>;})}<div className={GC(dark)} style={{marginTop:12,borderRadius:14,padding:12}}><div style={{fontSize:13,fontWeight:800,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:6}}>Challenge a Friend</div><button onClick={function(){if(!pid)return;var qs=shuffle(D).slice(0,10).map(function(c){return c.i;});createChallenge(pid,qs,md||"flags").then(function(c){if(c){setChalCode(c.code);var txt="GeoDojo Challenge: "+c.code+"\nhttps://geodojo.app";if(navigator.share)navigator.share({text:txt}).catch(function(){});else if(navigator.clipboard){navigator.clipboard.writeText(txt);alert("Code: "+c.code);}}}).catch(function(){});}} style={{width:"100%",padding:10,background:$.gld,color:"#FFF",borderRadius:12,fontSize:13,fontWeight:800,border:"none",boxShadow:"0 3px 0 0 "+$.gldD,marginBottom:6}}>Create Challenge</button>{chalCode&&<div style={{textAlign:"center",fontSize:12,fontWeight:800,color:$.gld,marginBottom:6}}>Code: {chalCode}</div>}<div style={{display:"flex",gap:4}}><input value={joinCode} onChange={function(e){setJoinCode(e.target.value.toUpperCase());}} placeholder="Code" style={{flex:1,padding:"8px 10px",borderRadius:10,border:"2px solid "+dk(dark,$.bdr,"#2A2A3E"),fontSize:13,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8"),background:dk(dark,"#FFF","#141420"),outline:"none"}} /><button onClick={function(){if(!joinCode)return;getChallenge(joinCode).then(function(c){if(c){setChalData(c);setChalMode(true);start(c.mode||"flags");}else alert("Not found");}).catch(function(){alert("Error");});}} style={{padding:"8px 14px",background:$.pri,color:"#FFF",borderRadius:10,fontSize:13,fontWeight:800,border:"none"}}>Join</button></div></div></div>}
{/* PROFILE */}
{scr==="profile"&&(function(){var earnedAch=ACHIEVEMENTS.filter(function(a){return a.check(ms,mc,bk);});return <div className="fadeUp"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><button onClick={function(){sS("home");}} style={{color:$.pri,fontSize:12,fontWeight:700}}>{"\u2190 "+t.back}</button><button onClick={function(){var url="https://geodojo.app/#/u/"+(uN||"player");if(navigator.share)navigator.share({url:url}).catch(function(){});else if(navigator.clipboard){navigator.clipboard.writeText(url);alert("Link copied!");}}} style={{color:$.blu,fontSize:11,fontWeight:700}}>Share</button></div><div className={GC(dark)} style={{borderRadius:18,padding:18,textAlign:"center",marginBottom:12}}><Logo size={56} /><div style={{fontSize:20,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8"),marginTop:8}}>{uN||"Explorer"}</div><div style={{display:"inline-flex",alignItems:"center",gap:4,padding:"3px 12px",background:belt.color+"15",borderRadius:10,marginTop:6}}><div style={{width:10,height:10,borderRadius:5,background:belt.color}} /><span style={{fontSize:11,fontWeight:700,color:belt.color}}>{bN(belt,lang)}</span></div><div style={{display:"flex",justifyContent:"center",gap:14,marginTop:10}}>{[[mc,t.mastered,$.pri],[bk,"Best",$.gld],[earnedAch.length,"Badges",$.blu]].map(function(item,i){return <div key={i} style={{textAlign:"center"}}><div style={{fontSize:20,fontWeight:900,color:item[2]}}>{item[0]}</div><div style={{fontSize:8,fontWeight:700,color:dk(dark,$.mu,"#666680"),textTransform:"uppercase"}}>{item[1]}</div></div>;})}</div></div><div style={{fontSize:12,fontWeight:800,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:6}}>Achievements ({earnedAch.length}/{ACHIEVEMENTS.length})</div>{ACHIEVEMENTS.map(function(a){var earned=a.check(ms,mc,bk);return <div key={a.id} className={GC(dark)} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:12,marginBottom:4,opacity:earned?1:0.35}}><div style={{width:30,height:30,borderRadius:8,background:earned?a.c:dk(dark,$.faint,"#1A1A2E"),display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:800,color:earned?"#FFF":dk(dark,$.mu,"#666680")}}>{a.icon}</div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:dk(dark,$.ink,"#F0F0F8")}}>{a.name[lang]||a.name.en}</div><div style={{fontSize:9,color:dk(dark,$.mu,"#666680")}}>{a.desc[lang]||a.desc.en}</div></div>{earned&&<div style={{width:16,height:16,borderRadius:8,background:$.ok,display:"flex",alignItems:"center",justifyContent:"center",color:"#FFF",fontSize:9}}>{"\u2713"}</div>}</div>;})}</div>;})()}
{/* STATS */}
{scr==="stats"&&<div className="fadeUp"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><button onClick={function(){sS("home");}} style={{color:$.pri,fontSize:12,fontWeight:700}}>{"\u2190 "+t.back}</button></div><h2 style={{fontSize:18,fontWeight:900,color:dk(dark,$.ink,"#F0F0F8"),marginBottom:8}}>{t.jour}</h2><div style={{display:"flex",gap:3,marginBottom:12}}>{BELTS.map(function(b,i){return <div key={i} style={{flex:1,height:8,borderRadius:4,background:mc>=b.min?b.color:dk(dark,$.faint,"#1A1A2E")}} />;})}</div>{CONTS.filter(function(z){return z!=="All";}).map(function(z){var cc=D.filter(function(c){return c.z===z;});var m=cc.filter(function(c){return gm(c.i)>=80;}).length;var p=cc.length?Math.round((m/cc.length)*100):0;return <div key={z} style={{marginBottom:6}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontSize:11,color:dk(dark,$.ink,"#F0F0F8"),fontWeight:600}}>{cl(z)}</span><span style={{fontSize:9,color:dk(dark,$.mu,"#666680"),fontWeight:700}}>{m}/{cc.length}</span></div><div style={{width:"100%",height:6,background:dk(dark,$.faint,"#1A1A2E"),borderRadius:3,overflow:"hidden"}}><div style={{width:p+"%",height:"100%",background:CC[z],borderRadius:3}} /></div></div>;})}</div>}
</div></div>);
}
